apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client-other
  namespace: client-prod
spec:
  workload:
    name: client-other
  calls:
    - kubernetes:
        kind: Deployment
        name: othersvc
